"""Add forum fields

Revision ID: 07e08a022f81
Revises: 67d30f31aa84
Create Date: 2025-06-18 14:07:06.897591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07e08a022f81'
down_revision: Union[str, None] = '67d30f31aa84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('official_posts', sa.Column('is_pinned', sa.Boolean(), nullable=True))
    op.add_column('official_posts', sa.Column('is_ama', sa.Boolean(), nullable=True))
    op.add_column('official_posts', sa.Column('tags', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('official_posts', 'tags')
    op.drop_column('official_posts', 'is_ama')
    op.drop_column('official_posts', 'is_pinned')
    # ### end Alembic commands ###
