"""add flag fields to RatingCategoryScore

Revision ID: 4588518b68fe
Revises: be2a980432eb
Create Date: 2025-06-19 09:45:26.904675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4588518b68fe'
down_revision: Union[str, None] = 'be2a980432eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rating_scores', sa.Column('flagged', sa.Boolean(), nullable=True))
    op.add_column('rating_scores', sa.Column('flag_reason', sa.String(length=1000), nullable=True))
    op.add_column('rating_scores', sa.Column('flagged_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'rating_scores', 'users', ['flagged_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rating_scores', type_='foreignkey')
    op.drop_column('rating_scores', 'flagged_by')
    op.drop_column('rating_scores', 'flag_reason')
    op.drop_column('rating_scores', 'flagged')
    # ### end Alembic commands ###
