"""Add state and county to RatedEntity

Revision ID: 4a4ae897b197
Revises: 5872cc6c1322
Create Date: 2025-06-17 11:12:36.726328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a4ae897b197'
down_revision: Union[str, None] = '5872cc6c1322'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rated_entities', sa.Column('state', sa.String(), nullable=True))
    op.add_column('rated_entities', sa.Column('county', sa.String(), nullable=True))
    op.create_index(op.f('ix_rated_entities_county'), 'rated_entities', ['county'], unique=False)
    op.create_index(op.f('ix_rated_entities_state'), 'rated_entities', ['state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rated_entities_state'), table_name='rated_entities')
    op.drop_index(op.f('ix_rated_entities_county'), table_name='rated_entities')
    op.drop_column('rated_entities', 'county')
    op.drop_column('rated_entities', 'state')
    # ### end Alembic commands ###
