"""Increase comment length to 2000

Revision ID: 9cb15ea00991
Revises: 4a4ae897b197
Create Date: 2025-06-17 15:26:02.562192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cb15ea00991'
down_revision: Union[str, None] = '4a4ae897b197'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rated_entities', 'state',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('rated_entities', 'county',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rated_entities', 'county',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('rated_entities', 'state',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
