"""Add violated_rights to rating scores

Revision ID: ab82da90aa09
Revises: 07e08a022f81
Create Date: 2025-06-18 19:38:12.862345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ab82da90aa09'
down_revision: Union[str, None] = '07e08a022f81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rating_scores', sa.Column('violated_rights', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rating_scores', 'violated_rights')
    # ### end Alembic commands ###
