name: Check Folder Structure

on:
  workflow_dispatch:

jobs:
  debug-folders:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print GitHub workspace path
        run: echo "Workspace = ${{ github.workspace }}"

      - name: List all folders and files
        run: |
          pwd
          ls -R
